site_name: Giovannelli Lab protocols
site_description: 'Protocols used in the Giovannelli Lab'
nav:
    - Giovannelli Lab Protocols: index.md
    - wet bench:
        - DNA extraction from sediments: wetbench_molbio_DNA_extraction_sediments.md
        - Shark genomic DNA extraction: wetbench_molbio_DNA_extraction_shark.md
        - Miniprep: wetbench_molbiol_miniprep.md
        - Antiobiogram test: wetbench_microbiol_antibiogram_protocol.md
        - Ammonia Nessler standard curve: wetbench_geochem_standard_curve_ammonia.md
        - Ammonia Nessler determination: wetbench_geochem_ammonia_determination.md
        - Total Prokaryotic numbers (FC): wetbench_TPN_sediments_flowcytometry.md
        - Total spores count sediments: wetbench_biochem_DPA_spores_sediments.md
        - Compertent Cells CaCl2: wetbench_molbiol_competent_cells_CaCl2.md
    - in silico:
        - Metaproteomic processing: insilico_metaproteomic.md

theme: mkdocs
formats: all
